1. 학습 날짜 // 

    2020-07-26(일)
 
2. 학습시간 // 

    16:00 ~ 20:00(자가)

3. 학습 범위 및 주제 // 
    
    python, 예외처리

4. 동료 학습 방법 (온라인 또는 오프라인으로 동료 학습이 이뤄진 경우, 어떤 식으로 이뤄졌는지 기술) // 오프라인으로 만난경우 각각 슬랙 아이디 // 온라인(슬랙, 스카이프, 카카오톡)으로 피드백을 받는 경우 피드백해준 자 ID // 

    온라인을 통해 동료학습 하였다. cpp에서 사용하는 오류처리 문법에 대해 질문하였다. 피드백해준 자 :gicho, jeonkim, sanhan, jungtlee, youcho, sanglee

5. 학습 목표 //

    python에서 예외처리에 대해 학습한다. 
    
6. 과제 제출 repository 주소 // 
    
    
    
7. 상세 학습 내용 (운영진 판단하에 학습 내용이 부진할 경우 재 제출 요구 예정) 필수사항 이외에 자유롭게 작성 가능 실제 코딩에 사용한 시간 (필수) 학습에 참고한 사이트 (홈페이지, 블로그, 동영상, 자료)와 간단한 내용(권고) 오늘 발견한 문제(버그, 몰랐던 것,...)와 해결 방안(필수) 다른 교육생들과의 협업, 토론 내용(권고) //
    
    19:00 ~ 20:00 동안 문제를 풀며 코드를 작성하였다.
    파이썬에서는 try, except, finally 구문을 이용하여 예외처리를 할 수 있다. try 블록 수행중 오류가 발생하면 except 블록이 수행된다. 오류가 발생하지 않는 경우 except 블록은 수행되지 않는다. 따라서 try 블록에 수행할 명령을 입력하고 except 블록 내부에 오류가 발생한 경우 처리에 대한 명령을 입력한다. finally문의 경우 오류의 발생여부와 관계없이 항상 실행된다. 
    
    except는 3가지 방식으로 사용할 수 있다. except: 의 경우 어떤 오류가 발생하더라도 except이 실행된다. except[발생오류]: 의 경우 미리 지정한 오류와 동일한 경우만 except이 실행된다. except[발생 오류 [as 오류 메시지 변수]]: 의 경우 오류메세지의 내용까지 알고 싶은 경우 사용한다. `except ZeroDivisionError as e:
    print(e)` 와 같이 사용되며 이때 "division by zero" 메세지가 출력된다.
    
    상황에 따라 파이썬 내장 오류인 NotImplementedError, 내장 클래스인 Exception을 이용하여 오류를 일부러 발생시킬 수 있다.
    
    (참고사이트 : https://wikidocs.net/30)
    
    
8. 학습 내용에 대한 개인적인 총평 (최소 5줄 이상) //

   파이썬에서는 오류를 처리하기 위해 try, exception 구문을 사용하였다. cpp에서는 try, catch를 사용한 것과 비교하여 사용하는 단어가 달랐고 exception이 더 잘 받아들여졌다. finally 구문은 어렵지 않으나 이번 기회를 통해 처음 알게 되었고 파일을 open 하고 close 하는 상황과 같이 오류 발생여부와 상관없이 항상 실행해야 되는 명령이 있을때 사용한다는 것을 알게 되었다. 
   
   except의 사용방법이 다양한 것이 특이하였다. 내가 원하는 오류만을 선택할 수 있었고 관련된 오류메세지를 출력할 수 있었다. 이를 이용하여 다양한 조건문에 활용할 수 있을 것으로 생각된다.
   
9. 다음 학습 계획 (최소 5줄 이상) // 
    
    42seoul 과제 이외에 개인적으로 자료구조 파이썬에 대해 학습한다.
    
    알고리즘 연습문제를 풀며 학습한다.
    
    cub3d에 대해 공부하고 평가를 받는다.